#!/usr/bin/env python3
"""Manage Dictait's local memory without opening an app window."""
import argparse
import json
import os
import tempfile
import uuid
from pathlib import Path
from memory import MemoryStore, SUPPORT


def load_personal():
    path = SUPPORT / "personalization.json"
    if not path.exists():
        return {"vocabulary": [], "examples": []}
    return json.loads(path.read_text(encoding="utf-8"))


def save_personal(value):
    SUPPORT.mkdir(parents=True, exist_ok=True)
    descriptor, filename = tempfile.mkstemp(dir=SUPPORT, prefix="personalization-", suffix=".tmp")
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as output:
            json.dump(value, output, ensure_ascii=False, indent=2)
            output.write("\n")
        os.replace(filename, SUPPORT / "personalization.json")
    finally:
        Path(filename).unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    add = subparsers.add_parser("add", help="Add a preferred term and optional spoken alias")
    add.add_argument("word")
    add.add_argument("--heard-as", default="")
    remove = subparsers.add_parser("remove", help="Remove a personal vocabulary term")
    remove.add_argument("word")
    subparsers.add_parser("list", help="List personal vocabulary")
    subparsers.add_parser("stats", help="Show graph/index sizes")
    search = subparsers.add_parser("search", help="Search saved notes; enable notes mode to save them")
    search.add_argument("query")
    export = subparsers.add_parser("export", help="Export wiki-linked Markdown for Obsidian")
    export.add_argument("directory", type=Path)
    forget = subparsers.add_parser("forget", help="Delete learned graph, saved notes and correction examples")
    forget.add_argument("--all", action="store_true", required=True)
    args = parser.parse_args()
    if args.command in {"add", "remove", "list"}:
        personal = load_personal()
        if args.command == "add":
            word, alias = args.word.strip(), args.heard_as.strip()
            if not word or len(word) > 80 or len(alias) > 80:
                parser.error("Use a word/phrase and alias of 1–80 characters.")
            entries = personal.setdefault("vocabulary", [])
            existing = next((e for e in entries if e["word"].casefold() == word.casefold()), None)
            if existing:
                existing.update(word=word, alias=alias)
            else:
                if len(entries) >= 200:
                    parser.error("Personal vocabulary is limited to 200 terms.")
                entries.append({"id": str(uuid.uuid4()), "word": word, "alias": alias, "learned": False})
            save_personal(personal)
            print(f"Remembered {word}. Applies to your next dictation.")
        elif args.command == "remove":
            personal["vocabulary"] = [e for e in personal.get("vocabulary", []) if e["word"].casefold() != args.word.strip().casefold()]
            save_personal(personal)
            print("Removed from personal vocabulary.")
        else:
            print(json.dumps(personal.get("vocabulary", []), ensure_ascii=False, indent=2))
        return
    memory = MemoryStore()
    try:
        if args.command == "stats":
            print(json.dumps(memory.stats(), indent=2))
        elif args.command == "search":
            print(json.dumps(memory.search(args.query), ensure_ascii=False, indent=2))
        elif args.command == "export":
            stats = memory.export_obsidian(args.directory)
            print(f"Exported {stats['terms']} terms and {stats['notes']} notes to {args.directory.resolve()}")
        elif args.command == "forget":
            # Remove only filenames generated by this app, preserving hand-written vault notes.
            filenames = [memory.term_filename(term, term_id) + ".md"
                         for term_id, term in memory.db.execute("SELECT id,term FROM terms")]
            import time
            filenames += [f"Dictation {time.strftime('%Y-%m-%d %H-%M-%S', time.localtime(created))}-{note_id[:8]}.md"
                          for note_id, created in memory.db.execute("SELECT id,created FROM notes")]
            for filename in filenames + ["Dictait.md", "graph.html"]:
                (memory.path.parent / "Notes" / filename).unlink(missing_ok=True)
            with memory.db:
                for table in ("note_terms", "links", "note_search", "notes", "term_search", "terms"):
                    memory.db.execute(f"DELETE FROM {table}")
            memory.db.execute("PRAGMA wal_checkpoint(TRUNCATE)")
            memory.db.execute("VACUUM")
            personal = load_personal()
            personal["examples"] = []
            save_personal(personal)
            print("Forgot learned terms, connections, notes and correction examples. Personal vocabulary and separately exported vaults were retained.")
    finally:
        memory.close()


if __name__ == "__main__":
    main()
